image: Visual Studio 2019

version: 1.0.0.{build}-rc

skip_branch_with_pr: true
skip_tags: true
skip_commits:
  files:
    - '**/*.md'

install:
  - choco install dotnetcore-sdk --version 3.0.100

environment:
  Appveyor: true
  # Postgres
  POSTGRES_PATH: C:\Program Files\PostgreSQL\10
  PGUSER: postgres
  PGPASSWORD: Password12!
  POSTGRES_ENV_POSTGRES_USER: postgres
  POSTGRES_ENV_POSTGRES_PASSWORD: Password12!
  POSTGRES_ENV_POSTGRES_DB: test
  # MySQL
  MYSQL_PATH: C:\Program Files\MySql\MySQL Server 5.7
  MYSQL_PWD: Password12!
  MYSQL_ENV_MYSQL_USER: root
  MYSQL_ENV_MYSQL_PASSWORD: Password12!
  MYSQL_ENV_MYSQL_DATABASE: test
services:
  - mssql2017
  - mysql
  - postgresql101

init:
  - git config --global core.autocrlf input
  - SET PATH=%POSTGRES_PATH%\bin;%MYSQL_PATH%\bin;%PATH%

nuget:
  disable_publish_on_pr: true

build_script:
  # Postgres
  - createdb test
  # MySQL
  - mysql -e "create database test;" --user=root
  # Our stuff
  - ps: .\build.ps1 -PullRequestNumber "$env:APPVEYOR_PULL_REQUEST_NUMBER" -CreatePackages $true

test: off
artifacts:
  - path: .\.nupkgs\*.nupkg

deploy:
- provider: NuGet
  server: https://www.myget.org/F/dapper-database/api/v2
  on:
    branch: master  
  api_key:
    secure: omw4IBzq0RAzx+QBqt880QN9gJUB3aB+GpX8bizQxirNDk+Ocw66b+8wtf8Eu2SK
  symbol_server: https://www.myget.org/F/dapper-database/symbols/api/v2/package
